### ISSUE TITLE
Unable to authenticate after receiving an invite

### ISSUE THREAD

**Issue by KremmerSeb** [rbytr/rbytr#19]
Users are not able to authenticate with the link sent via email after invitation. Instead they see a 404. I guess, authentication after invitation is not implemented yet.

**Comment by hueper** [comment]
Thanks a lot @KremmerSeb for opening an issue. I'm already working on that. Should be fixed and delivered today.

**Comment by hueper** [comment]
@KremmerSeb could you test, please?
