### ISSUE TITLE
Comment and uncomment on a post

### ISSUE THREAD

**Issue by hueper** [rbytr/rbytr#2]
User should be able to comment and uncomment on a post

**Comment by DanielPerlman** [comment]
should the comment listing contain the user profile picture?

**Comment by hueper** [comment]
I'd like to have thumbnail, name of commenting user and date of commenting

**Comment by hueper** [comment]
@DanielPerlman 
user is not able to comment on someone else's post (getting a 403)

**Comment by DanielPerlman** [comment]
I'll take a look

**Comment by hueper** [comment]
could you fix those styling issues too?

![screenshot-commenting](https://cloud.githubusercontent.com/assets/6799184/19075207/305b9e7e-8a44-11e6-94f7-1d40821244bf.jpg)

**Comment by hueper** [comment]
@DanielPerlman thanks for your latest changes. What do you think about this:

How about seeing comments as special posts, save them just like posts but flag them with "isComment:true"?
So we could "like" and "share" comments too and apply tasks to comments as well. So in future, posts could be pushed to target networks not only with pre-likes and -shares but also along with (pre-)comments.

**Comment by DanielPerlman** [comment]
@hueper I definitely feel like that's a really good idea, one question is how it would show up on the interface? Or would that be only for backend use? So the comment would be displayed the same way it is now but we would be able to do extra things on the backend? 

Or, the other way would be to actually display comments as posts too, with something special indicating they're a comment and also with some kind of reference to the post they are connected to, maybe a little dropdown box displaying the original post or even just a button "Go to post" that takes the user to the original?

**Comment by hueper** [comment]
@DanielPerlman 
I'd like to merge, close this issue and refer to #28: "comments as special posts". 
PR?
