### ISSUE TITLE
App setup errors

### ISSUE THREAD

**Issue by george-i** [rbytr/rbytr#26]
I've just cloned the app and this is a list of errors I get, which may not be linked to my computer configuration:

- missing module "config\env\development"
- error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was not found. Is Visual Studio required?

A setup, installation readme would be required.

**Comment by hueper** [comment]
Hi @george-i,
thank you!

Installation guide will come next week.

**Comment by hueper** [comment]
@george-i WDYT?

**Comment by george-i** [comment]
The README looks good, however, I found it a bit confusing initially, so it needs to be cleaned a bit.
The [Before You Begin](https://github.com/rbytr/rbytr#before-you-begin) section is copied from MEAN.JS README, which is in a different context.
Overall is much better.

**Comment by george-i** [comment]
After following the readme recommendations, the installation went well.
