### ISSUE TITLE
Grunt Errors after type command "grunt"

### ISSUE THREAD

**Issue by a-alrihawi** [rbytr/rbytr#30]
Error: Cannot find module './url-file-manager'
Error: Cannot find module './util/estraverse'

**Comment by hueper** [comment]
in windows env,

![capture](https://cloud.githubusercontent.com/assets/6799184/19366237/a08f7e14-9196-11e6-839f-b9968e53b870.PNG)

**Comment by a-alrihawi** [comment]
**Solution:**

I removed old Github repository and I re cloned it again. 

after that I execute two commands:

`npm install `
`bower install `

Unfortunately, I have got one grunt warning  with "**sass**", so I installed Ruby, then I installed **sass**
using **gem** ,
with this command:
`gem install sass`

after that **grunt** work correctly.
